# Site settings
title: Akash Gupta personal website
description: A website about my all projects and profiles
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: AKASH GUPTA
user_description: Hi, I am a computer science graduate student at Illinois Institute of Technology, Chicago. I am actively seeking full time software engineer opportunity.
user_title: Software Developer
email: akash@hawk.iit.edu
twitter_username: akash22gupta
github_username:  akash22gupta
facebook_username:  akash22gupta
linkedin_username:  akash22gupta


# Google-analytics
google-analytics:
  id: "UA-120517137-1"

exclude: ['package.json', 'src' , 'node_modules']
