# Site settings
title: Akash Gupta personal website
description: A website about my all projects and profiles
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hey! I'm Akash
user_description: Software developer at Discover Financial Services, designing, developing, maintaining, and optimizing some cool Restful microservices/applications having 4+ years of experience in Software Development.
user_title: Software Developer Open To Work
email: akash.22gupta@gmail.com
github_username:  akash22gupta
facebook_username:  akash22gupta
linkedin_username:  akash22gupta


# Google-analytics
google-analytics:
  id: "UA-120517137-1"

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman
